/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CertificationEntryForm: typeof import('./src/components/resume-form/CertificationEntryForm.vue')['default']
    CertificationsSection: typeof import('./src/components/resume-form/CertificationsSection.vue')['default']
    EducationEntryForm: typeof import('./src/components/resume-form/EducationEntryForm.vue')['default']
    EducationSection: typeof import('./src/components/resume-form/EducationSection.vue')['default']
    ExperienceEntryForm: typeof import('./src/components/resume-form/ExperienceEntryForm.vue')['default']
    ExperienceSection: typeof import('./src/components/resume-form/ExperienceSection.vue')['default']
    FormNav: typeof import('./src/components/resume-form/FormNav.vue')['default']
    ImportExportBar: typeof import('./src/components/resume-preview/ImportExportBar.vue')['default']
    LanguageEntryForm: typeof import('./src/components/resume-form/LanguageEntryForm.vue')['default']
    LanguagesSection: typeof import('./src/components/resume-form/LanguagesSection.vue')['default']
    OptionsSection: typeof import('./src/components/resume-form/OptionsSection.vue')['default']
    PersonalSection: typeof import('./src/components/resume-form/PersonalSection.vue')['default']
    PreviewSection: typeof import('./src/components/resume-preview/PreviewSection.vue')['default']
    ProjectEntryForm: typeof import('./src/components/resume-form/ProjectEntryForm.vue')['default']
    ProjectsSection: typeof import('./src/components/resume-form/ProjectsSection.vue')['default']
    ResumeFormPanel: typeof import('./src/components/resume-form/ResumeFormPanel.vue')['default']
    ResumePreview: typeof import('./src/components/resume-preview/ResumePreview.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SkillsSection: typeof import('./src/components/resume-form/SkillsSection.vue')['default']
    SummarySection: typeof import('./src/components/resume-form/SummarySection.vue')['default']
    UAlert: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Alert.vue')['default']
    UApp: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UButton: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UCheckbox: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Checkbox.vue')['default']
    UFormField: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/FormField.vue')['default']
    UInput: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Input.vue')['default']
    UPopover: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Popover.vue')['default']
    USwitch: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Switch.vue')['default']
    UTabs: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Tabs.vue')['default']
    UTextarea: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Textarea.vue')['default']
  }
}
